### ISSUE TITLE
403 error when running ez_setup.py

### ISSUE THREAD

**Issue by wangzhizheng** [EMCECS/ECS-CommunityEdition#138]
in file:
/ecs-multi-node/step1_ecs_multinode_install.py line572
os.system("docker "+' '.join(DockerCommandLineFlags)+" exec -t  ecsmultinode python ez_setup.py --insecure")

[root@ECS01 ~]# python ez_setup.py --insecure
Traceback (most recent call last):
  File "ez_setup.py", line 425, in <module>
    sys.exit(main())
  File "ez_setup.py", line 421, in main
    archive = download_setuptools(**_download_args(options))
  File "ez_setup.py", line 336, in download_setuptools
    version = _resolve_version(version)
  File "ez_setup.py", line 357, in _resolve_version
    resp = urlopen(meta_url)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Proxy Unacknowledged

Is this file still valid?
or any additional settings needed?
I am running it from EMC network.

**Comment by wangzhizheng** [comment]
close this issue because it can not be reproduced again.
not sure why have this kind of error, maybe something wrong with VPN.
if ez_setup doesn't work, I still can install setuptools manually
