### ISSUE TITLE
Step1 Installation Fails 

### ISSUE THREAD

**Issue by VMMan** [EMCECS/ECS-CommunityEdition#14]
Team,

Does the single node install script support LVM volumes?  Could this be causing my Step1 script failure below?  After the script exits, I do have a correctly formatted volume: 

/dev/vdb1 on /ecs/uuid-1 type xfs (rw,relatime,seclabel,attr2,inode64,noquota)

Thanks for any help with this,
Dave

[25/Aug/2015 21:53:10] INFO [root:261] Partitioning the disk '/dev/vdb'
Device does not contain a recognized partition table
Building a new DOS disklabel with disk identifier 0xd7e051ce.
[25/Aug/2015 21:53:10] INFO [root:269] Make File filesystem in '/dev/vdb1'
meta-data=/dev/vdb1              isize=256    agcount=4, agsize=33554368 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=0        finobt=0
data     =                       bsize=4096   blocks=134217472, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=0
log      =internal log           bsize=4096   blocks=65535, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
[25/Aug/2015 21:53:21] INFO [root:274] Make /ecs/uuid-1 Directory in attached Volume
[25/Aug/2015 21:53:21] INFO [root:278] Mount attached /dev/dev/vdb1 to /ecs/uuid-1 volume.
[25/Aug/2015 21:53:21] INFO [root:298] Executing the additional preparation script in '/dev/vdb1'
[25/Aug/2015 21:53:21] ERROR [root:302] [Errno 13] Permission denied
Traceback (most recent call last):
  File "step1_ecs_singlenode_install.py", line 299, in run_additional_prep_file_func
    subprocess.call([prep_file_name, device_name])
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
[25/Aug/2015 21:53:21] CRITICAL [root:303] Aborting program! Please review log.

**Comment by padthaitofuhot** [comment]
My first idea is it looks like the additional_prep.sh script isn't running.  Does it have execute permissions?  If so, re-run it with bash command tracing on and grab all the output:

bash -x additional_prep.sh | tee trace.log 2>&1

**Comment by VMMan** [comment]
Lol, thanks Travis!  additional_prep.sh didn't have execute permissions.  Script ran fine after umounting my object store device and rerunning it.

Thanks Again for the quick help :)
D

**Comment by padthaitofuhot** [comment]
Anytime.  There's a a fix for it, so it shouldn't bother anyone else.  Or you, if you update your local repo. :+1:
