### ISSUE TITLE
Adding NFS export results in 500 error for one bucket

### ISSUE THREAD

**Issue by spirilis** [EMCECS/ECS-CommunityEdition#189]
I have a single-node docker install on a CentOS VM which I've been toying with.  It has 3 disks assigned to it, and I just went through the process of creating a bucket & assigning an NFS export.

Namespace: spir
Bucket: home_spirilis

Some UID/GID mappings are set up in the File page under the portal:
spirilis -> uid 1000
users -> gid 100
wheel -> gid 0

Creating an NFS export for /spir/home_spirilis/ with the following export:
Host: apollo.lan
Summary: rw,async,authsys,alldir,anonuid=spirilis,anongid=users,root=spirilis

I get a 500 error:
Error 999 (http: 500): An unexpected error occurred, please check the ECS logs for more information. Internal Service Error

This bucket is empty BTW.  If I delete the bucket and re-create a whole new bucket with the SAME NAME, I get the same error when creating an NFS export.

However, I have 3 other buckets on this system named "personal", "test_one", "test_two" for which I've created exports with the same settings (same host, same export parameters) and they all worked great.  Fwiw some of these buckets have notification quotas, some don't, doesn't seem to affect it.

Pouring over logs I see a few entries (warning: big logdump)

```
ecsportalsvc.log:{"path":"/spir/home_spirilis/","export-options":[{"host":"apollo.lan","security":"rw,async,authsys,alldir,anonuid=spirilis,anongid=users,root=spirilis"}]}
provisionsvc-error.log:2017-02-25T18:08:31,954 [pool-56-thread-3-c0a80005:15a75e6357f:10f:25] ERROR  EngineKeyValueStore.java (line 172) Failed to fetch key ExportEntry:/spir/home_spirilis/ due to com.emc.storageos.data.object.exception.ObjectControllerException: remote hit internal error, request c0a80005:15a75e61f81:e6:e8, ip 192.168.0.5:9888
provisionsvc.log:  path: "/spir/home_spirilis/"
provisionsvc.log:2017-02-25T18:08:31,954 [pool-56-thread-3-c0a80005:15a75e6357f:10f:25] ERROR  EngineKeyValueStore.java (line 172) Failed to fetch key ExportEntry:/spir/home_spirilis/ due to com.emc.storageos.data.object.exception.ObjectControllerException: remote hit internal error, request c0a80005:15a75e61f81:e6:e8, ip 192.168.0.5:9888
```

Grepping for that request ID "c0a80005:15a75e61f81:e6:e8" further:
```
provisionsvc-error.log:2017-02-25T18:08:31,953 [pool-56-thread-3-c0a80005:15a75e6357f:10f:25] ERROR  RoutingClientBase.java (line 1030) sendAndWaitForResponseWithRetryAndUpdate hit an exception for request [c0a80005:15a75e61f81:e6:e8, 192.168.0.5, 9888] server com.emc.storageos.data.object.exception.ObjectControllerException: remote hit internal error, request c0a80005:15a75e61f81:e6:e8, ip 192.168.0.5:9888
provisionsvc-error.log:2017-02-25T18:08:31,954 [pool-56-thread-3-c0a80005:15a75e6357f:10f:25] ERROR  EngineKeyValueStore.java (line 172) Failed to fetch key ExportEntry:/spir/home_spirilis/ due to com.emc.storageos.data.object.exception.ObjectControllerException: remote hit internal error, request c0a80005:15a75e61f81:e6:e8, ip 192.168.0.5:9888
provisionsvc-error.log:2017-02-25T18:08:31,955 [pool-56-thread-3-c0a80005:15a75e6357f:10f:25] ERROR  NFSBucketAccessAPIServer.java (line 232) Failed to add export entry remote hit internal error, request c0a80005:15a75e61f81:e6:e8, ip 192.168.0.5:9888
provisionsvc.log:2017-02-25T18:08:31,952 [pool-56-thread-3-c0a80005:15a75e6357f:10f:25]  WARN  RoutingClientBase.java (line 640) Request failed, server 192.168.0.5:9888, key [CoS: urn:storageos:VirtualArray:e307947e-3292-4bbc-8d44-5cae0cb97ffc, type: RT, keyHash: 6764, level: 0], requestId c0a80005:15a75e61f81:e6:e8, Process ResourceSvc, com.emc.storageos.data.object.exception.ObjectControllerException: remote hit internal error, request c0a80005:15a75e61f81:e6:e8, ip 192.168.0.5:9888
provisionsvc.log:2017-02-25T18:08:31,953 [pool-56-thread-3-c0a80005:15a75e6357f:10f:25] ERROR  RoutingClientBase.java (line 1030) sendAndWaitForResponseWithRetryAndUpdate hit an exception for request [c0a80005:15a75e61f81:e6:e8, 192.168.0.5, 9888] server com.emc.storageos.data.object.exception.ObjectControllerException: remote hit internal error, request c0a80005:15a75e61f81:e6:e8, ip 192.168.0.5:9888
provisionsvc.log:2017-02-25T18:08:31,954 [pool-56-thread-3-c0a80005:15a75e6357f:10f:25] ERROR  EngineKeyValueStore.java (line 172) Failed to fetch key ExportEntry:/spir/home_spirilis/ due to com.emc.storageos.data.object.exception.ObjectControllerException: remote hit internal error, request c0a80005:15a75e61f81:e6:e8, ip 192.168.0.5:9888
provisionsvc.log:2017-02-25T18:08:31,955 [pool-56-thread-3-c0a80005:15a75e6357f:10f:25] ERROR  NFSBucketAccessAPIServer.java (line 232) Failed to add export entry remote hit internal error, request c0a80005:15a75e61f81:e6:e8, ip 192.168.0.5:9888
provisionsvc.out:com.emc.storageos.data.object.exception.ObjectControllerException: remote hit internal error, request c0a80005:15a75e61f81:e6:e8, ip 192.168.0.5:9888
resourcesvc-error.log:2017-02-25T18:08:31,945 [TaskScheduler-ResourceSvc-COMMUNICATOR-ParallelExecutor-097-c0a80005:15a75e6357f:10f:25] ERROR  AbstractDirectoryRequestHandler.java (line 106) Failed to process command REQUEST_FILEKEYVAL_GET from request c0a80005:15a75e61f81:e6:e8
resourcesvc-error.log:2017-02-25T18:08:31,946 [TaskScheduler-ResourceSvc-COMMUNICATOR-ParallelExecutor-097-c0a80005:15a75e6357f:10f:25] ERROR  RemoteRequestProcessorResourceSvc.java (line 80) handleRequest, id c0a80005:15a75e61f81:e6:e8 type REQUEST_FILEKEYVAL_GET, error
resourcesvc.log:2017-02-25T18:08:31,945 [TaskScheduler-ResourceSvc-COMMUNICATOR-ParallelExecutor-097-c0a80005:15a75e6357f:10f:25] ERROR  AbstractDirectoryRequestHandler.java (line 106) Failed to process command REQUEST_FILEKEYVAL_GET from request c0a80005:15a75e61f81:e6:e8
resourcesvc.log:2017-02-25T18:08:31,946 [TaskScheduler-ResourceSvc-COMMUNICATOR-ParallelExecutor-097-c0a80005:15a75e6357f:10f:25] ERROR  RemoteRequestProcessorResourceSvc.java (line 80) handleRequest, id c0a80005:15a75e61f81:e6:e8 type REQUEST_FILEKEYVAL_GET, error
resourcesvc.log:2017-02-25T18:08:31,951 [TaskScheduler-ResourceSvc-COMMUNICATOR-ParallelExecutor-097-c0a80005:15a75e6357f:10f:25]  WARN  AbstractRequestProcessor.java (line 219) failure processing remote request ID c0a80005:15a75e61f81:e6:e8
```

The only logfile error that looks like it's not just passing the buck is what I see in resourcesvc.log, so here's more detail on that:
```
2017-02-25T18:08:31,945 [TaskScheduler-ResourceSvc-COMMUNICATOR-ParallelExecutor-097-c0a80005:15a75e6357f:10f:25] ERROR  AbstractDirectoryRequestHandler.java (line 106) Failed to process command REQUEST_FILEKEYVAL_GET from request c0a80005:15a75e61f81:e6:e8
com.google.protobuf.UninitializedMessageException: Message missing required fields: keyId, value
        at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:770)
        at com.emc.storageos.data.object.filesvc.FileSvc$FileKeyValInfo$Builder.build(FileSvc.java:417)
        at com.emc.storageos.data.protocol.resource.FileSvcSerializer.fromUpdateMetadataRecord(FileSvcSerializer.java:79)
        at com.emc.storageos.data.object.impl.resource.ResourceDirectoryImpl.getFileKey(ResourceDirectoryImpl.java:2864)
        at com.emc.storageos.data.object.directoryService.impl.resource.FileSvcDirectoryRequestHandler.handleGetFileKey(FileSvcDirectoryRequestHandler.java:101)
        at com.emc.storageos.data.object.directoryService.impl.resource.FileSvcDirectoryRequestHandler.doHandle(FileSvcDirectoryRequestHandler.java:45)
        at com.emc.storageos.data.object.directoryService.impl.resource.AbstractResourceDirectoryRequestHandler.handleRequest(AbstractResourceDirectoryRequestHandler.java:65)
        at com.emc.storageos.data.object.directoryService.impl.AbstractDirectoryRequestHandler.handleRequest(AbstractDirectoryRequestHandler.java:88)
        at com.emc.storageos.data.object.directoryService.impl.CompositeDirectoryRequestHandler.handleRequest(CompositeDirectoryRequestHandler.java:53)
        at com.emc.storageos.data.object.directoryService.impl.RemoteRequestProcessorResourceSvc.handleRequest(RemoteRequestProcessorResourceSvc.java:71)
        at com.emc.storageos.data.object.communicator.AbstractRequestProcessor.handleRemoteRequest(AbstractRequestProcessor.java:212)
        at com.emc.storageos.data.object.communicator.impl.RemoteOperationProcessor$RequestProcessor.run(RemoteOperationProcessor.java:288)
        at com.emc.storageos.data.object.communicator.impl.RemoteOperationProcessor$RequestProcessor.call(RemoteOperationProcessor.java:266)
        at com.emc.storageos.data.object.communicator.impl.RemoteOperationProcessor$RequestProcessor.call(RemoteOperationProcessor.java:256)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-02-25T18:08:31,946 [TaskScheduler-ResourceSvc-COMMUNICATOR-ParallelExecutor-097-c0a80005:15a75e6357f:10f:25] ERROR  RemoteRequestProcessorResourceSvc.java (line 80) handleRequest, id c0a80005:15a75e61f81:e6:e8 type REQUEST_FILEKEYVAL_GET, error
com.emc.storageos.data.object.exception.ObjectControllerException: request REQUEST_FILEKEYVAL_GET processing failed
        at com.emc.storageos.data.object.directoryService.impl.AbstractDirectoryRequestHandler.handleRequest(AbstractDirectoryRequestHandler.java:110)
        at com.emc.storageos.data.object.directoryService.impl.CompositeDirectoryRequestHandler.handleRequest(CompositeDirectoryRequestHandler.java:53)
        at com.emc.storageos.data.object.directoryService.impl.RemoteRequestProcessorResourceSvc.handleRequest(RemoteRequestProcessorResourceSvc.java:71)
        at com.emc.storageos.data.object.communicator.AbstractRequestProcessor.handleRemoteRequest(AbstractRequestProcessor.java:212)
        at com.emc.storageos.data.object.communicator.impl.RemoteOperationProcessor$RequestProcessor.run(RemoteOperationProcessor.java:288)
        at com.emc.storageos.data.object.communicator.impl.RemoteOperationProcessor$RequestProcessor.call(RemoteOperationProcessor.java:266)
        at com.emc.storageos.data.object.communicator.impl.RemoteOperationProcessor$RequestProcessor.call(RemoteOperationProcessor.java:256)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-02-25T18:08:31,951 [TaskScheduler-ResourceSvc-COMMUNICATOR-ParallelExecutor-097-c0a80005:15a75e6357f:10f:25]  WARN  AbstractRequestProcessor.java (line 219) failure processing remote request ID c0a80005:15a75e61f81:e6:e8
com.emc.storageos.data.object.exception.ObjectControllerException: request REQUEST_FILEKEYVAL_GET processing failed
        at com.emc.storageos.data.object.directoryService.impl.AbstractDirectoryRequestHandler.handleRequest(AbstractDirectoryRequestHandler.java:110)
        at com.emc.storageos.data.object.directoryService.impl.CompositeDirectoryRequestHandler.handleRequest(CompositeDirectoryRequestHandler.java:53)
        at com.emc.storageos.data.object.directoryService.impl.RemoteRequestProcessorResourceSvc.handleRequest(RemoteRequestProcessorResourceSvc.java:71)
        at com.emc.storageos.data.object.communicator.AbstractRequestProcessor.handleRemoteRequest(AbstractRequestProcessor.java:212)
        at com.emc.storageos.data.object.communicator.impl.RemoteOperationProcessor$RequestProcessor.run(RemoteOperationProcessor.java:288)
        at com.emc.storageos.data.object.communicator.impl.RemoteOperationProcessor$RequestProcessor.call(RemoteOperationProcessor.java:266)
        at com.emc.storageos.data.object.communicator.impl.RemoteOperationProcessor$RequestProcessor.call(RemoteOperationProcessor.java:256)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-02-25T18:08:32,534 [ZkConnection-41]  INFO  ZkConnection.java (line 216) check for changes in /data/vnest/vnest-main/configuration/coord-client
2017-02-25T18:08:34,092 [client-heart-beat-monitor-000]  INFO  ClientHeartBeatImpl.java (line 66) start hb run
2017-02-25T18:08:38,560 [TaskList-000]  INFO  PaxosClient.java (line 295) maintenance done on deleteConfirm c: 0 t: 2 a: 5000, removed 0 keys
2017-02-25T18:08:39,399 [TaskScheduler-ResourceSvc-VARRAY_VALIDITY_CHECKER-ScheduledExecutor-000]  INFO  VarrayValidityChecker.java (line 71) Updating the in-memory varray cache
2017-02-25T18:08:39,402 [TaskScheduler-ResourceSvc-VARRAY_VALIDITY_CHECKER-ScheduledExecutor-000]  INFO  VarrayValidityChecker.java (line 86) Updating varray urn:storageos:VirtualArray:e307947e-3292-4bbc-8d44-5cae0cb97ffc New State INITIALIZED
2017-02-25T18:08:39,652 [TaskScheduler-ResourceSvc-DefaultScheduler-004]  INFO  BufferManagerImpl.java (line 142) Buffer stats: inactive buffer pool info:
free buffer pool info:
active buffer pool info:
Buffer: [bufferId:0, offset:124877, refCount:0
```

Any hints or ideas where else I should look?

**Comment by felipersantos** [comment]
Hi 

im with the same problem.

Regards

**Comment by padthaitofuhot** [comment]
Hello and thank you for your patience.  I'm pinging other repo members who may have more information on this NFS issue.

**Comment by padthaitofuhot** [comment]
Hi @spirilis
Please capture around a 1000 lines of resourcesvc.log while recreating this issue and post the output here so we can take a look at it.  Thanks!

**Comment by padthaitofuhot** [comment]
This issue is closing due to inactivity.  Please reopen if we can be of further assistance.  Thank you.
