### ISSUE TITLE
While running island-step3 It got Stuck

### ISSUE THREAD

**Issue by ashishdixit18** [EMCECS/ECS-CommunityEdition#363]
### Expected Behavior

Creating Storage Pool: vdc1/sp1
Traceback (most recent call last):
  File "/usr/local/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.4.0', 'console_scripts', 'ecsconfig')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/ecsconfig.py", line 627, in sp
    tasks = add_all()
  File "/usr/local/bin/ecsconfig.py", line 603, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/local/bin/ecsconfig.py", line 583, in add_one
    sp_id = sp_create(name, conf.ecs.sp_ecs_options(name))
  File "/usr/local/bin/ecsconfig.py", line 547, in sp_create
    resp = conf.api_client.storage_pool.create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/ecsclient/common/provisioning/storage_pool.py", line 109, in create
    return self.conn.post('vdc/data-services/varrays', json_payload=payload)
  File "/usr/local/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/local/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: Operation cannot be performed due to entered varray sp1 conflicts with existing sp1 - Bad request body: https://10.248.81.174:4443/vdc/data-services/varrays 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo
>

### Output

**Comment by padthaitofuhot** [comment]
You'll either need to login to the Web UI and configure the storage pool by hand or refresh the deployment.

If you want to refresh the deployment, run the following sequence:
```
ecsremove purge-nodes
island-step2
island-step3
```

**Comment by padthaitofuhot** [comment]
Closing this issue due to inactivity.  Please reopen if you would like additional assistance.  Thanks!
