### ISSUE TITLE
object/user-secret-keys/object_admin occasionally throws an HTTP 500

### ISSUE THREAD

**Issue by padthaitofuhot** [EMCECS/ECS-CommunityEdition#371]
### Expected Behavior

No error, users are created.

### Actual Behavior
 
Occasionally this happens:
```
ecsclient.common.exceptions.ECSClientException: An error occurred in the API service. Cause: error getting user secret key. - An error occurred in the API Service: https://10.1.83.116:4443/object/user-secret-keys/object_admin1 500 Server Error  [first 60 chars of response] {"code":7000,"retryable":false,"description":"An error occur
```
### Steps to Reproduce Behavior

Create users with `ecsconfig` such as in `step2`

### Output

```
> Creating all configured object users:
> Creating all object users
> Creating 'object_admin1' in namespace 'ns1'
> 	Adding object_admin1's S3 credentials
Traceback (most recent call last):
  File "/usr/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.5.0', 'console_scripts', 'ecsconfig')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/ecsconfig.py", line 1152, in object_user
    add_all()
  File "/usr/bin/ecsconfig.py", line 1118, in add_all
    add_one(this_name)
  File "/usr/bin/ecsconfig.py", line 1131, in add_one
    secret_key=ou_dict['s3_secret_key'])
  File "/usr/lib/python2.7/site-packages/ecsclient/common/user_management/secret_key.py", line 110, in create
    return self.conn.post(url, json_payload=payload)
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: An error occurred in the API service. Cause: error getting user secret key. - An error occurred in the API Service: https://10.1.83.116:4443/object/user-secret-keys/object_admin1 500 Server Error  [first 60 chars of response] {"code":7000,"retryable":false,"description":"An error occur
```

**Comment by padthaitofuhot** [comment]
Resolved by #376
