### ISSUE TITLE
ECS Mgmt Portal not running in ECS CE 3.1.0.1

### ISSUE THREAD

**Issue by vchrisb** [EMCECS/ECS-CommunityEdition#383]
### Expected Behavior
ECS Mgmt Portal reachable

### Actual Behavior
In a fresh installation of ECS Community Edition Install Node 2.5.1 (ECS 3.1.0.1), using the OVA, the ECS Mgmt Portal is not reachable. This is true for single node and multi node deployments.
`step1` and `step2` do run successfully.

### Steps to Reproduce Behavior
fresh deployment

### Output
`ecsportalsvc.log`
```
2017-11-09 13:14:18,795 [main]  INFO  Logger.java (line 308) Starting /opt/storageos/ecsportal
2017-11-09 13:14:21,904 [main]  INFO  Logger.java (line 308) Application is precompiled
2017-11-09 13:14:38,088 [main]  WARN  Logger.java (line 367) Messages file missing for locale en
2017-11-09 13:14:38,090 [main]  INFO  Logger.java (line 308) Application 'ui' is now started !
2017-11-09 13:14:38,618 [main]  INFO  Logger.java (line 308) Listening for HTTPS at /127.0.0.1:64443  ...
2017-11-09 13:15:36,058 [play-thread-1] ERROR  Logger.java (line 604)
java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:649)
        at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
        at org.jboss.netty.handler.ssl.SslHandler.flushPendingEncryptedWrites(SslHandler.java:767)
        at org.jboss.netty.handler.ssl.SslHandler.wrap(SslHandler.java:711)
        at org.jboss.netty.handler.ssl.SslHandler.handleDownstream(SslHandler.java:446)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:68)
        at org.jboss.netty.channel.Channels.write(Channels.java:632)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.discard(ChunkedWriteHandler.java:165)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:258)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:123)
        at org.jboss.netty.channel.Channels.write(Channels.java:611)
        at org.jboss.netty.channel.Channels.write(Channels.java:578)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:259)
        at play.server.FileService.serve(FileService.java:67)
        at play.server.PlayHandler.copyResponse(PlayHandler.java:453)
        at Invocation.HTTP Request(Play!)
```

**Comment by padthaitofuhot** [comment]
Please update your OVA or git repo to 2.5.2 and try that.  I've been unable to duplicate the issue as reported.
