### ISSUE TITLE
ECS STEP2 issue: Error while registering 1 commodity node(s) 

### ISSUE THREAD

**Issue by fawazalobaidan** [EMCECS/ECS-CommunityEdition#446]
```
# Output and Logs go here
> Creating Storage Pool: vdc1/sp1
>              OK
> Adding Data Stores to Storage Pool:
>              vdc1/sp1/172.17.99.69
Traceback (most recent call last):
  File "/usr/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.8.0.post0', 'console_scripts', 'ecsconfig')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/ecsconfig.py", line 661, in sp
    tasks = add_all()
  File "/usr/bin/ecsconfig.py", line 637, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/bin/ecsconfig.py", line 629, in add_one
    sp_tasks.append(sp_add_node(sp_id, node))
  File "/usr/bin/ecsconfig.py", line 606, in sp_add_node
    return conf.api_client.data_store.create(**kwargs)
  File "/usr/lib/python2.7/site-packages/ecsclient/common/provisioning/data_store.py", line 217, in create
    return self.conn.post('vdc/data-stores/commodity', json_payload=payload)
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: Error while registering 1 commodity node(s) - Bad request body: https://172.17.99.69:4443/vdc/data-stores/commodity 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo



---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by padthaitofuhot** [comment]
Hello, it appears the initial VDC failed to register the storage pool.  Please run the following commands to reset the deployment:
```
# ecsremove purge-nodes
# step1
# step2
```
If you are using the OVA, then please use the `ova-step1`  and `ova-step2` commands.  Thank you.

**Comment by ach-coo** [comment]
I'm encountering this error too:

> ecsclient.common.exceptions.ECSClientException: Error while registering 1 commodity node(s) - Bad request body: https://10.238.148.63:4443/vdc/data-stores/commodity 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo


I'm installing island, so I tried:

```
# ecsremove purge-nodes
# island-step2
# island-step3
```

but I get the same error.
