### ISSUE TITLE
step2 Could not generate token for user:root

### ISSUE THREAD

**Issue by LucasGhost** [EMCECS/ECS-CommunityEdition#476]
### Expected Behavior
step2 completed

### Actual Behavior
(Please put additional output and logs in the section for that below)
step2 failed on error: 

> Non-200 status returned (500) - Could not generate token for user: root - `

### Steps to Reproduce Behavior

1. latest ECS cloned from git
2. standard installation [with internet via proxy] step1 completed successfully
3. step2 failed on error above

### Relevant Output and Logs
during first step2 execution - this error was generated during storage pool creation: 
> Pinging Management API Endpoint until ready
> Pinging endpoint 10.1.95.16... (CTRL-C to break)
> PONG: api_endpoint=10.1.95.16 username=root diag_endpoint=10.1.95.16 dt_total=0 dt_unready=0 dt_unknown=0

> Installing licensing in ECS VDC(s)
> Using default license
> Adding licensing to VDC: VDC_ESET
>       OK
> Added default license to ECS

> Pinging Management API Endpoint until ready
> Pinging endpoint 10.1.95.16... (CTRL-C to break)
> PONG: api_endpoint=10.1.95.16 username=root diag_endpoint=10.1.95.16 dt_total=0 dt_unready=0 dt_unknown=0

`> Creating Storage Pool: VDC_ESET/SP_local
Traceback (most recent call last):
  File "/usr/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.9.1.post0', 'console_scripts', 'ecsconfig')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/ecsconfig.py", line 661, in sp
    tasks = add_all()
  File "/usr/bin/ecsconfig.py", line 637, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/bin/ecsconfig.py", line 617, in add_one
    sp_id = sp_create(name, conf.ecs.sp_ecs_options(name))
  File "/usr/bin/ecsconfig.py", line 575, in sp_create
    resp = conf.api_client.storage_pool.create(**kwargs)
  File "/usr/lib/python2.7/site-packages/ecsclient/common/provisioning/storage_pool.py", line 109, in create
    return self.conn.post('vdc/data-services/varrays', json_payload=payload)
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 143, in _request
    headers=self._fetch_headers(),
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 106, in _fetch_headers
    token = self.token if self.token else self._token_request.get_token()
  File "/usr/lib/python2.7/site-packages/ecsclient/common/token_request.py", line 106, in get_token
    return self.get_new_token()
  File "/usr/lib/python2.7/site-packages/ecsclient/common/token_request.py", line 79, in get_new_token
    raise ECSClientException.from_response(req, message=msg)
ecsclient.common.exceptions.ECSClientException: Non-200 status returned (500) - Could not generate token for user: root`

when i tried to rerun step2: it gave me same error already in licensing phase: 

`> Pinging Management API Endpoint until ready
> Pinging endpoint 10.1.95.16... (CTRL-C to break)
> PONG: api_endpoint=10.1.95.16 username=root diag_endpoint=10.1.95.16 dt_total=0 dt_unready=0 dt_unknown=0

> Installing licensing in ECS VDC(s)
> Using default license
> Adding licensing to VDC: VDC_ESET
> FATAL: Could not add default license
> Non-200 status returned (500) - Could not generate token for user: root - An unexpected error occurred, please check the ViPR logs for more information: https://10.1.95.16:4443/login 500 Server Error  [first 60 chars of response] {"code":999,"retryable":false,"description":"An unexpected e
`

same when i called just ecsconfig licensing

`(testing) root@chlebicek01.eset.corp:/emc/ECS-CommunityEdition $ ecsconfig licensing -a
> Installing licensing in ECS VDC(s)
> Using default license
> Adding licensing to VDC: VDC_ESET
> FATAL: Could not add default license
> Non-200 status returned (500) - Could not generate token for user: root - An unexpected error occurred, please check the ViPR logs for more information: https://10.1.95.16:4443/login 500 Server Error  [first 60 chars of response] {"code":999,"retryable":false,"description":"An unexpected e
`

```
# Output and Logs go here
```

---
Notifies: @captntuttle

**Comment by LucasGhost** [comment]
Hi, 
today i tried to run step2 again, just to recheck if the output will be the same. I executed step2 and i didnt receive error above again, but still it failed shortly after during adding nodes to VDC. 
 
 ```
Pinging endpoint 10.1.95.16... (CTRL-C to break)
  PONG: api_endpoint=10.1.95.16 username=root diag_endpoint=10.1.95.16 dt_total=0 dt_unready=0 dt_unknown=0
  Installing licensing in ECS VDC(s)
  Using default license
  Adding licensing to VDC: VDC_ESET
        OK
  Added default license to ECS
  Pinging Management API Endpoint until ready
  Pinging endpoint 10.1.95.16... (CTRL-C to break)
  PONG: api_endpoint=10.1.95.16 username=root diag_endpoint=10.1.95.16 dt_total=0 dt_unready=0 dt_unknown=0
  Creating Storage Pool: VDC_ESET/SP_local
        OK
  Adding Data Stores to Storage Pool:
        VDC_ESET/SP_local/10.1.95.16

Traceback (most recent call last):

 File "/usr/bin/ecsconfig", line 11, in <module>

   load_entry_point('ecsdeploy==2.9.1.post0', 'console_scripts', 'ecsconfig')()

 File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__

   return self.main(*args, **kwargs)

 File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main

   rv = self.invoke(ctx)

 File "/usr/lib/python2.7/site-packages/click/core.py", line 1163, in invoke

   rv.append(sub_ctx.command.invoke(sub_ctx))

 File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke

   return ctx.invoke(self.callback, **ctx.params)

 File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke

   return callback(*args, **kwargs)

 File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func

   return ctx.invoke(f, obj, *args, **kwargs)

 File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke

   return callback(*args, **kwargs)

 File "/usr/bin/ecsconfig.py", line 661, in sp

   tasks = add_all()

 File "/usr/bin/ecsconfig.py", line 637, in add_all

   sp_tasks.extend(add_one(name))

 File "/usr/bin/ecsconfig.py", line 629, in add_one

   sp_tasks.append(sp_add_node(sp_id, node))

 File "/usr/bin/ecsconfig.py", line 606, in sp_add_node

   return conf.api_client.data_store.create(**kwargs)

 File "/usr/lib/python2.7/site-packages/ecsclient/common/provisioning/data_store.py", line 217, in create

   return self.conn.post('vdc/data-stores/commodity', json_payload=payload)

 File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post

   return self._request(url, json_payload, http_verb='POST')

 File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request

   raise ECSClientException.from_response(req)

ecsclient.common.exceptions.ECSClientException: Error while registering 1 commodity node(s) - Bad request body: https://10.1.95.16:4443/vdc/data-stores/commodity 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo
```

When i try to rerun step2 again, it just fails because it tells me that storage pool with SP_local is already created, so im not sure, if i need to start from scratch again, or is there any way how to continue//fix this.

**Comment by captntuttle** [comment]
I will take a look at this as soon as I can - very strange behavior, but until then I suggest you roll back the installation with `ecsremove purge-nodes` and then re-run `step1`. After step1 is complete give it a few minutes (maybe 15) before running `step2`.

**Comment by LucasGhost** [comment]
Hi Ken, thanks for your help.

I did purge-nodes command, but now when running step1 i get this error:

```
 [WARNING]: error in 'jsonfile' cache plugin while trying to read /var/cache/emc/ecs-install/facts/10.1.95.16 : Expecting value: line 1 column 1 (char 0). Most likely a corrupt file, so erasing and failing.

ERROR! Error while decoding the cache file /var/cache/emc/ecs-install/facts/10.1.95.16: The cache file /var/cache/emc/ecs-install/facts/10.1.95.16 was corrupt, or did not otherwise contain valid data. It has been removed, so you can re-run your command now.
```

I noticed this error in the past as well, it looks like that purging is not completely correct, i think only way how i fixed it in the previous tries, was just to purge all and start from scratch.

**Comment by LucasGhost** [comment]
Just to update, i tried everything from scratch again, but i got same error : 

`ecsclient.common.exceptions.ECSClientException: Error while registering 1 commodity node(s) - Bad request body: https://10.1.95.16:4443/vdc/data-stores/commodity 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo`

**Comment by captntuttle** [comment]
Thanks @LucasGhost I'll take a look at at this as soon as I get a chance.
