### ISSUE TITLE
 Error while registering 1 commodity node(s)

### ISSUE THREAD

**Issue by saradadremio** [EMCECS/ECS-CommunityEdition#498]
Step2 always fails and throws below exception
> Adding Data Stores to Storage Pool:
> 	vdc1/sp1/172.25.0.45
Traceback (most recent call last):
  File "/usr/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.9.1.post0', 'console_scripts', 'ecsconfig')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/ecsconfig.py", line 661, in sp
    tasks = add_all()
  File "/usr/bin/ecsconfig.py", line 637, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/bin/ecsconfig.py", line 629, in add_one
    sp_tasks.append(sp_add_node(sp_id, node))
  File "/usr/bin/ecsconfig.py", line 606, in sp_add_node
    return conf.api_client.data_store.create(**kwargs)
  File "/usr/lib/python2.7/site-packages/ecsclient/common/provisioning/data_store.py", line 217, in create
    return self.conn.post('vdc/data-stores/commodity', json_payload=payload)
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: Error while registering 1 commodity node(s) - Bad request body: https://172.25.0.45:4443/vdc/data-stores/commodity 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo

#  Steps to Reproduce Behavior

1. ./bootstrap.sh -y -g -c deploy.yml
2. reboot
3. step1
4. step2

---
Notifies: @captntuttle

**Comment by captntuttle** [comment]
this is usually caused by running step2 before the api services are fully ready to go. when seeing this I advise you wait about 10 minutes after running step1 and try again.

**Comment by salieri11** [comment]
@captntuttle I have the same issue. I waited 2 hours before running step2.

**Comment by captntuttle** [comment]
@salieri11 The API isn't coming up... Can you confirm sufficient resources on the node?

**Comment by salieri11** [comment]
@captntuttle I am using the minimal configuration just to see if it works. 16 RAM, 4 cores, 150gb block storage and 16gb root storage.

**Comment by salieri11** [comment]
on AWS machines, using Centos 7.7

**Comment by kentakoga** [comment]
Encountered the same issue using the ova installation. Failed on ova-step2 with this error.  Giving the system more time to initialize didn't help. Left for the day, tried the next morning, same issue.

**Comment by salieri11** [comment]
eventually I ended up with going back to centos 7.5 and it worked

**Comment by sahmed1501** [comment]
The OVA file (ECS appliance file) has built in OS so how did you go back to centos 7.5?
I am having the same problem.
