### ISSUE TITLE
Failed to deploy ECS 3.3.0 OVA

### ISSUE THREAD

**Issue by stonezdj** [EMCECS/ECS-CommunityEdition#501]
### Expected Behavior

Success to install ECS

### Actual Behavior
After ova-step2, it failed with error message: "Bad request body"

### Steps to Reproduce Behavior

1. Import and clone the [ECS 3.3.0 OVA!](http://131118670375936839.public.ecstestdrive.com/public/dellemc-ecsce-3.3.0-install-node.ova)
2. videploy
```
# deploy.yml reference implementation v2.8.0

# [Optional]
# By changing the license_accepted boolean value to "true" you are
# declaring your agreement to the terms of the license agreement
# contained in the license.txt file included with this software
# distribution.
licensing:
  license_accepted: false

#autonames:
#  custom:
#    - ecs01
#    - ecs02
#    - ecs03
#    - ecs04
#    - ecs05
#    - ecs06

# [Required]
# Deployment facts reference
facts:

  # [Required]
  # Node IP or resolvable hostname from which installations will be launched
  # The only supported configuration is to install from the same node as the
  # bootstrap.sh script is run.
  # NOTE: if the install node is to be migrated into an island environment,
  #       the hostname or IP address listed here should be the one in the
  #       island environment.
  install_node: 10.160.219.84

  # [Required]
  # IPs of machines that will be whitelisted in the firewall and allowed
  # to access management ports of all nodes. If this is set to the
  # wildcard (0.0.0.0/0) then anyone can access management ports.
  management_clients:
    - 0.0.0.0/0

  # [Required]
  # These credentials must be the same across all nodes. Ansible uses these credentials to
  # gain initial access to each node in the deployment and set up ssh public key authentication.
  # If these are not correct, the deployment will fail.
  ssh_defaults:
    # [Required]
    # Username to use when logging in to nodes
    ssh_username: admin
    # [Required]
    # Password to use with SSH login
    # *** Set to same value as ssh_username to enable SSH public key authentication ***
    ssh_password: ChangeMe
    # [Required when enabling SSH public key authentication]
    # Password to give to sudo when gaining root access.
    ansible_become_pass: ChangeMe
    # [Required]
    # Select the type of crypto to use when dealing with ssh public key
    # authentication. Valid values here are:
    #  - "rsa" (Default)
    #  - "ed25519"
    ssh_crypto: rsa

  # [Required]
  # Environment configuration for this deployment.
  node_defaults:
    dns_domain: local
    dns_servers:
      - 10.117.0.1
    ntp_servers:
      - ntp.google.com
    #
    # [Optional]
    # VFS path to source of randomness
    # Defaults to /dev/urandom for speed considerations.  If you prefer /dev/random, put that here.
    # If you have a /dev/srandom implementation or special entropy hardware, you may use that too
    # so long as it implements a /dev/random type device.
    entropy_source: /dev/urandom
    #
    # [Optional]
    # Picklist for node names.
    # Available options:
    #  - "moons" (ECS CE default)
    #  - "cities" (ECS SKU-flavored)
    #  - "custom" (uncomment and use the top-level autonames block to define these)
    # autonaming: custom

    #
    # [Optional]
    # If your ECS comes with differing default credentials, you can specify those here
    # ecs_root_user: root
    # ecs_root_pass: ChangeMe

  # [Optional]
  # Storage pool defaults. Configure to your liking.
  # All block devices that will be consumed by ECS on ALL nodes must be listed under the
  # ecs_block_devices option. This can be overridden by the storage pool configuration.
  # At least ONE (1) block device is REQUIRED for a successful install. More is better.
  storage_pool_defaults:
    is_cold_storage_enabled: false
    is_protected: false
    description: Default storage pool description
    ecs_block_devices:
      - /dev/sdb

  # [Required]
  # Storage pool layout. You MUST have at least ONE (1) storage pool for a successful install.
  storage_pools:
    - name: sp1
      members:
        - 10.160.219.84
      options:
        is_protected: false
        is_cold_storage_enabled: false
        description: My First SP
        ecs_block_devices:
          - /dev/sdb

  # [Optional]
  # VDC defaults. Configure to your liking.
  virtual_data_center_defaults:
    description: Default virtual data center description

  # [Required]
  # Virtual data center layout. You MUST have at least ONE (1) VDC for a successful install.
  # Multi-VDC deployments are not yet implemented
  virtual_data_centers:
    - name: vdc1
      members:
        - sp1
      options:
        description: My First VDC

  # [Optional]
  # Replication group defaults. Configure to your liking.
  replication_group_defaults:
    description: Default replication group description
    enable_rebalancing: true
    allow_all_namespaces: true
    is_full_rep: false

  # [Optional, required for namespaces]
  # Replication group layout. You MUST have at least ONE (1) RG to provision namespaces.
  replication_groups:
    - name: rg1
      members:
        - vdc1
      options:
        description: My First RG
        enable_rebalancing: true
        allow_all_namespaces: true
        is_full_rep: false

  # [Optional]
  # Management User defaults
  management_user_defaults:
    is_system_admin: false
    is_system_monitor: false

  # [Optional]
  # Management Users
  management_users:
    - username: admin1
      password: ChangeMe
      options:
        is_system_admin: true
    - username: monitor1
      password: ChangeMe
      options:
        is_system_monitor: true

  # [Optional]
  # Namespace defaults
  namespace_defaults:
    is_stale_allowed: false
    is_compliance_enabled: false

  # [Optional]
  # Namespace layout
  namespaces:
    - name: ns1
      replication_group: rg1
      administrators:
        - root
      options:
        is_stale_allowed: false
        is_compliance_enabled: false

  # [Optional]
  # Object User defaults
  object_user_defaults:
    # Comma-separated list of Swift authorization groups
    swift_groups_list:
      - users
    # Lifetime of S3 secret key in minutes
    s3_expiry_time: 2592000

  # [Optional]
  # Object Users
  object_users:
    - username: object_admin1
      namespace: ns1
      options:
        swift_password: ChangeMe
        swift_groups_list:
          - admin
          - users
        s3_secret_key: ChangeMeChangeMeChangeMeChangeMeChangeMe
        s3_expiry_time: 2592000
    - username: object_user1
      namespace: ns1
      options:
        swift_password: ChangeMe
        s3_secret_key: ChangeMeChangeMeChangeMeChangeMeChangeMe

  # [Optional]
  # Bucket defaults
  bucket_defaults:
    namespace: ns1
    replication_group: rg1
    head_type: s3
    filesystem_enabled: False
    stale_allowed: False
    encryption_enabled: False
    owner: object_admin1

  # [Optional]
  # Bucket layout (optional)
  buckets:
    - name: bucket1
      options:
        namespace: ns1
        replication_group: rg1
        owner: object_admin1
        head_type: s3
        filesystem_enabled: False
        stale_allowed: False
        encryption_enabled: False
```

3. ova-step1

4. ova-step2

### Relevant Output and Logs
```
it outputs error:
```
> 	vdc1/sp1/10.160.219.84
Traceback (most recent call last):
  File "/usr/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.9.1.post0', 'console_scripts', 'ecsconfig')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/ecsconfig.py", line 661, in sp
    tasks = add_all()
  File "/usr/bin/ecsconfig.py", line 637, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/bin/ecsconfig.py", line 629, in add_one
    sp_tasks.append(sp_add_node(sp_id, node))
  File "/usr/bin/ecsconfig.py", line 606, in sp_add_node
    return conf.api_client.data_store.create(**kwargs)
  File "/usr/lib/python2.7/site-packages/ecsclient/common/provisioning/data_store.py", line 217, in create
    return self.conn.post('vdc/data-stores/commodity', json_payload=payload)
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: Error while registering 1 commodity node(s) - Bad request body: https://10.160.219.84:4443/vdc/data-stores/commodity 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo
```
```

---
Notifies: @captntuttle

**Comment by captntuttle** [comment]
90% of the time this error pops up because step1 has completed but all of the APIs are not quite ready. Best bet is to wait about 10 minutes after step1 has completed before running step2.

**Comment by stonezdj** [comment]
Thanks @captntuttle, I rerun 
```
ecsremove purge-nodes
ova-step1
```
It failed with new error message:
```
RUNNING HANDLER [CentOS_7_baseline_install : CentOS 7 | Set the clock] *****************************
fatal: [10.160.219.84]: FAILED! => {"changed": true, "cmd": ["ntpd", "-gq"], "delta": "0:00:00.013096", "end": "2019-12-16 23:17:23.802943", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2019-12-16 23:17:23.789847", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

```

**Comment by captntuttle** [comment]
looks like it's having an issue with the ntp server... if you don't trust that you can purge the cache with ecsremove purge-all
