### ISSUE TITLE
Docker installation documents missing parameter UserName

### ISSUE THREAD

**Issue by jasoncwik** [EMCECS/ECS-CommunityEdition#58]
The table of parameters for running the step2 script is missing the 'UserName' parameter in both the single-node and multi-node instructions.

**Comment by jasoncwik** [comment]
Even worse, it doesn't say that, it fails with an exception: 
```
Traceback (most recent call last):
  File "step2_object_provisioning.py", line 349, in <module>
    main(sys.argv[1:])
  File "step2_object_provisioning.py", line 276, in main
    print("UserName: %s" %UserName)
UnboundLocalError: local variable 'UserName' referenced before assignment
```

**Comment by padthaitofuhot** [comment]
This should be a fast fix, if it isn't fixed already.  Please someone (Magdy? Adrian?) check it out?
